### ISSUE TITLE
Conditioning on dragWidth is ugly

### ISSUE THREAD

**Issue by ProfJanetDavis** [WhitmanSWDesignSpring2018/project-5-8-teamuno#32]
An alternative is to create an invisible 5x10 px rectangle at the end of each notebar to handle dragging the width of the note. These rectangles would need to be layered in front of the notebars proper.

https://github.com/WhitmanSWDesignSpring2018/project-5-8-teamuno/blob/99a47abe150e72bb26d8ff83ed114b279d365e87/src/tunecomposer/NoteBar.java#L132

**Comment by twolds** [comment]
We will be leaving this in.
