### ISSUE TITLE
Abstract methods in TuneRectangle should be documented with Javadoc

### ISSUE THREAD

**Issue by ProfJanetDavis** [WhitmanSWDesignSpring2018/project-5-8-teamuno#46]
https://github.com/WhitmanSWDesignSpring2018/project-5-8-teamuno/blob/256287ae65f9a25c20f8ccad76ec990698d916cc/src/tunecomposer/TuneRectangle.java#L22

**Comment by beszel** [comment]
Duplicate of the more general #56
