### ISSUE TITLE
Document empty methods

### ISSUE THREAD

**Issue by ProfJanetDavis** [WhitmanSWDesignSpring2018/project-5-8-teamuno#48]
Why is this method empty and not abstract? Please explain.

https://github.com/WhitmanSWDesignSpring2018/project-5-8-teamuno/blob/256287ae65f9a25c20f8ccad76ec990698d916cc/src/tunecomposer/TuneRectangle.java#L66

**Comment by beszel** [comment]
The `delete` method has been made abstract.
