### ISSUE TITLE
groupSelection and ungroupSelected should have parallel names

### ISSUE THREAD

**Issue by ProfJanetDavis** [WhitmanSWDesignSpring2018/project-5-8-teamuno#55]
For a more consistent interface 

https://github.com/WhitmanSWDesignSpring2018/project-5-8-teamuno/blob/6d6be5db01199b1cec40b85ff29c3d2ee3d9cdb3/src/tunecomposer/Composition.java#L88

**Comment by beszel** [comment]
Fixed this
