### ISSUE TITLE
All classes should have JavaDoc

### ISSUE THREAD

**Issue by ProfJanetDavis** [WhitmanSWDesignSpring2018/project-5-8-teamuno#56]
And authorship should be up to date

https://github.com/WhitmanSWDesignSpring2018/project-5-8-teamuno/blob/6d6be5db01199b1cec40b85ff29c3d2ee3d9cdb3/src/tunecomposer/CreationCommand.java#L9

**Comment by beszel** [comment]
I think I've taken care of all javadocs.
